version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  spring-app:
    container_name: spring-app
    build: ./AFTAS
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db

  angular-app:
    container_name: angular-app
    image: brief8springbootangular-angular-app
    ports:
      - "4200:4200"
    depends_on:
      - spring-app
    environment:
      SPRING_HOST: spring-app
